### ISSUE TITLE
Hi, great work, am trying to understand how I use in a real word app.

### ISSUE THREAD

**Issue by ejpusa-zz** [dvdhpkns/SFAuthenticationSession-Instagram-Oauth#1]
Thanks for putting this online. I'm confused a bit as compared to the "old way" of doing things, no live web site needed. If this is sent to the App store, I have to give users a web site address vs localhost?

Also there a few settings, I'm thinking one of them is off, getting this error message when try to login to 'the gram:

<img width="756" alt="screen shot 2017-08-07 at 9 39 12 pm" src="https://user-images.githubusercontent.com/1279819/29052572-fe0de320-7bb8-11e7-950f-3d8dc592fc68.png">
<img width="786" alt="screen shot 2017-08-07 at 9 38 52 pm" src="https://user-images.githubusercontent.com/1279819/29052570-fe0b38aa-7bb8-11e7-814f-e6f747819f3a.png">
<img width="343" alt="screen shot 2017-08-07 at 9 38 41 pm" src="https://user-images.githubusercontent.com/1279819/29052571-fe0d6d00-7bb8-11e7-8aa6-01724c150dd5.png">

<img width="816" alt="screen shot 2017-08-07 at 9 44 20 pm" src="https://user-images.githubusercontent.com/1279819/29052684-a2ddf6e2-7bb9-11e7-85a9-41db749e62ca.png">

**Comment by dvdhpkns** [comment]
Glad to help @ejpusa. 
When you mention the "old way", how have you done authentication previously? 
The purpose of the server is just to act as a pass through for the oauth redirect, because instagram will not allow you to put a custom URI scheme like `myapp://ouath_callback` so you must redirect to a web address. If there is a way to get around this, then you could redirect directly into the app and not need the server component. I suspect there are services that exist to handle this, but haven't looked into it. 
The error you are seeing is because the redirect url you are using in the app `http://localhost:5000/callback` does not match the one supplied to instagram `http://localhost.com`.
